theme: jekyll-theme-cayman
title: Fannie Vaquero's CV
description: <a href="https://drive.google.com/viewer?url=https://raw.githubusercontent.com/Magnus167/cv/pdf/Magnus167_CV.pdf">View PDF</a>
              &#124; <a href="https://raw.githubusercontent.com/Magnus167/cv/pdf/Magnus167_CV.pdf">Download PDF</a> 
              &#124; <a href="https://Magnus167.github.io/cv/resume_pdf.htm?src=https://raw.githubusercontent.com/Magnus167/cv/main/index.md">View Markdown</a>
github:
  is_project_page: false
