name: convert

on:
  push:
    branches: [main]

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build book
        with:
          output_branch: pdf
        run: |
          npm install -g md-to-pdf
          echo "Generating PDF"

          curl https://cdn.jsdelivr.net/gh/sindresorhus/github-markdown-css@4/github-markdown.min.css > ghmd.css

          curl https://cdn.jsdelivr.net/gh/PrismJS/prism@1/themes/prism.min.css > prism.css

          # combine the two files into one
          cat ghmd.css prism.css > style.css

          # get repo owner name
          repo_owner=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          # save as repo_owner_CV.pdf
          cat index.md | md-to-pdf --stylesheet "style.css" > $repo_owner\_CV.pdf



          ######################################


          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # if output_branch exists, delete it
          git branch -D $output_branch || true
          git checkout -b $output_branch
          # add the pdf to the repo
          git add .
          git commit -m "Add PDF"
          # push the pdf to the repo
          git push origin $output_branch
