name: Save PDF

on:
  push:
    branches: [main]

jobs:
  savepdf:
    name: Build PDF
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.repository }}
      OUTPUT_BRANCH: pdf2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all branches and tags
      - name: Set git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Install dependencies
        run: |
          pip install pdfkit
          sudo apt-get install wkhtmltopdf

      # change branch to pdf. if pdf branch exists, delete it and create a new one
      - name: Checkout pdf branch
        run: |
          if git show-ref --verify --quiet refs/heads/$OUTPUT_BRANCH; then
            git branch -D $OUTPUT_BRANCH
          fi
          git checkout -b $OUTPUT_BRANCH

      - name: Write Python script
        run: |
          echo "import pdfkit, os" > convert.py
          echo "repoOwner, repoName = os.getenv('REPO_NAME').split('/')" >> convert.py
          echo "pdfkit.from_url(f'https://.github.io/{repoName}/md.html?src=https://raw.githubusercontent.com/{repoOwner}/{repoName}/main/index.md', f'{repoOwner}_CV.pdf')" >> convert.py

      - name: Convert to PDF
        run: |
          python convert.py

      - name: Commit
        run: |
          git add $REPO_OWNER\_CV.pdf
          git commit -m "Update CV"

      - name: Push
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push origin $OUTPUT_BRANCH --force
